[param]
interface_type = "uart"
comport_uart = "COM8"
speed_uart = "2000000"
speed_jlink = "1000"
chip_xtal = "Auto"
ota = ""
version = ""
aes_key = ""
aes_iv = ""
addr = "0x0"
publickey = ""
privatekey = ""

[check_box]
ckb_erase_all = "False"
partition_download = true
encrypt = false
sign = false
single_download = false
auto_efuse_verify = false

[input_path]
img_bin_input = ""
pt_table_bin_input = ""
publickey = ""
privatekey = ""
