encrypt_type-group0 = "None"
key_sel-group0 = "0"
cache_way_disable-group0 = "None"
sign_type-group0 = "None"
crc_ignore-group0 = "False"
hash_ignore-group0 = "False"
encrypt_key-group0 = ""
aes_iv-group0 = ""
public_key_cfg-group0 = ""
private_key_cfg-group0 = ""
page_type = "mcu"
publickey = ""
privatekey = ""
dl_device = "uart"
dl_comport = "COM6"
dl_comspeed = "2000000"
dl_jlinkspeed = "1000"
dl_chiperase = "False"
dl_xtal = "Auto"
boot_src = "Flash"
img_type = "SingleCPU"
img1_addr = "0x2000"
img1_file = "D:/Software/bouffalo/bouffalo_sdk/examples/helloworld/build/build_out/helloworld_bl616.bin"
device_tree = "D:/Software/bouffalo/BouffaloLabDevCube-v1.9.0/chips/bl616/device_tree/bl_factory_params_IoTKitA_auto.dts"
mcu_clk = "WIFIPLL 320M"
flash_clk_type = "XTAL"
xtal_type = "XTAL_Auto"

[Image]
dl_device = "uart"
dl_comport = ""
dl_comspeed = "2000000"
dl_jlinkspeed = "1000"
dl_chiperase = "False"
dl_xtal = "Auto"
boot_src = "Flash"
img_type = "SingleCPU"
img1_addr = "0x2000"
img1_file = "D:\\Software\\bouffalo\\bouffalo_sdk\\examples\\helloworld\\build\\build_out\\boot2_bl616_isp_release_v8.1.8.bin"
device_tree = "D:/Software/bouffalo/BouffaloLabDevCube-v1.9.0/chips/bl616/device_tree/bl_factory_params_IoTKitA_auto.dts"
